"""Add aqi_30_minute_history table

Revision ID: b760d686cca3
Revises: b45fb5d26004
Create Date: 2025-09-07 08:32:09.573618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b760d686cca3'
down_revision = 'b45fb5d26004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aqi_30_minute_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aqi_location_id', sa.Integer(), nullable=False),
    sa.Column('measure_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aqi_location_id'], ['aqi_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aqi_30_minute_history_measure_time'), 'aqi_30_minute_history', ['measure_time'], unique=False)
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_aqi_30_minute_history_measure_time'), table_name='aqi_30_minute_history')
    op.drop_table('aqi_30_minute_history')
    # ### end Alembic commands ###