"""empty message

Revision ID: fe6555dfaa68
Revises: 
Create Date: 2025-09-07 17:30:04.570136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe6555dfaa68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aqi_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.Text(), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=False),
    sa.Column('serial_no', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('firmware_version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_id'), 'task_logs', ['id'], unique=False)
    op.create_index(op.f('ix_task_logs_task_name'), 'task_logs', ['task_name'], unique=False)
    op.create_table('aqi_30_minute_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aqi_location_id', sa.Integer(), nullable=False),
    sa.Column('measure_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aqi_location_id'], ['aqi_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aqi_30_minute_history_measure_time'), 'aqi_30_minute_history', ['measure_time'], unique=False)
    op.create_table('aqi_5_minute_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aqi_location_id', sa.Integer(), nullable=False),
    sa.Column('measure_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aqi_location_id'], ['aqi_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aqi_5_minute_history_measure_time'), 'aqi_5_minute_history', ['measure_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aqi_5_minute_history_measure_time'), table_name='aqi_5_minute_history')
    op.drop_table('aqi_5_minute_history')
    op.drop_index(op.f('ix_aqi_30_minute_history_measure_time'), table_name='aqi_30_minute_history')
    op.drop_table('aqi_30_minute_history')
    op.drop_index(op.f('ix_task_logs_task_name'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_table('aqi_location')
    # ### end Alembic commands ###